### ISSUE TITLE
Summary screen

### ISSUE THREAD

**Issue by laureD19** [DARIAH-ERIC/dariah-unr#19]
The summary screen should include the following information/fields:

### Summary of the KPIs presented in previous screens:
- Number of partner institutions
- Number of contributors at national level (calculated field based on reports.contributionsCount + sum of the contributions per country without endDate)
- Number of large meetings (event_reports.largeMeetings)
- Number of medium sized meetings (event_reports.mediumMeetings)
- Number of small meetings (event_reports.smallMeetings)
- Number of DARIAH Commissioned Event (event_reports.dariahCommissionedEvent)
- National website URL (URL from the outreach table - for type "national website". Most of the time will only be one URL, but it can be that some countries declare several) 
- Social Media (list of the "social media" type names coming from the outreach table)
- Number of small community services (based on service_kpis.value and service_sizes.type "small")
- Number of medium community services (based on service_kpis.value and service_sizes.type "medium")
- Number of large community services (based on service_kpis.value and service_sizes.type "large")
- Number of core services (based on service_kpis.value and service_sizes.type "core")

### Cost calculation (financial value of the national in-kind contribution)
- Option A - here NCs should be able to provide an int as input - @vronk I don't see the corresponding field in the data model - should also the reports.operationalCost be used here?
- Option B - calculated field - reports.operationalCost
- In-Kind contribution threshold (reports.operationalCostThreshold)

The calculation for option B should be based on the following: 
number of contributions.role = nationalCoordinator * roles.annualValue for nationalCoordinator
+
number of contributions.role = JRCmember * roles.annualValue for JRC member
+
number of contributions.role = WG Chair * roles.annualValue for WG Chair
+
number of event_reports.largeMeetings * value for large meeting (missing table?? @vronk )
+
number of event_reports.mediumMeetings * value for medium meeting (missing table??)
+
number of event_reports.smallMeetings * value for small meeting (missing table??)
+
number of event_reports.dariahCommissionedEvent * value for dariahCommissionedEvent (missing table??)
+
1 * value for national website (where @vronk )
+
1 * value for social media (where @vronk )
+
number of small services * serviceSize.annualValue for small services
+
number of medium services * serviceSize.annualValue for medium services
+
number of large services * serviceSize.annualValue for large services
+
number of core services * serviceSize.annualValue for core services

-----
Placeholder texts for this sreen will be added in the [dedicated discussion thread, here](https://github.com/DARIAH-ERIC/dariah-unr/discussions/15). 

@ArnaudRoi @vronk , Ed please comment - I'm not sure of this suggestion.

**Comment by vronk** [comment]
>     * Option A - here NCs should be able to provide an int as input - @vronk I don't see the corresponding field in the data model - should also the reports.operationalCost be used here?

yes.

> * value for large meeting (missing table?? @vronk ) + number of event_reports.mediumMeetings * value for medium meeting (missing table??) + number of event_reports.smallMeetings * value for small meeting (missing table??) + number of event_reports.dariahCommissionedEvent * value for dariahCommissionedEvent (missing table??)

that indeed went missing. It is now re-added: https://github.com/DARIAH-ERIC/dariah-unr/pull/21/files

> + 1 * value for national website(where @vronk ) + 1 * value for social media (where @vronk ) 

as discussed on slack, options are:
a) dirty: add it as two extra rows to the service-size table. (as it is in the policy).
b) purist: have a separate outreachCost table, with distinction by outreachType
but given that it should not be multiplied, it probably would not be of much help to really connect the outreach and outreachCost table

**Comment by vronk** [comment]
also we agreed that the formula should be serialized as a string in the field 
`Report.operationalCostDetail    String?`
for reproducibility, given that the various values will change every year.

Alternative would be to temporalize all the values, which would complicate the data model, IMO unnecessarily.

**Comment by vronk** [comment]
> @ArnaudRoi @vronk , Ed please comment - I'm not sure of this suggestion.

The calculation looks sane to me.
